server:
  port: 8006
  display-name: bz_merchant
  clientNo: BZ00007
spring:  
  profiles:  
    active: test
################################################测试环境配置#######################################################
---                                                       
spring:
  profiles: test
  aop:
    proxy-target-class: true
###########数据源配置#######################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.202:3306/bz_merchant?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: bztest
    password: bz123456
#############dubbo配置###########################    
  dubbo: 
   application:
     name: fileService-provider
   base-package: com.bz.merchant.core.service # dubbo服务发布者所在的包
   registry:
     address: 192.168.2.202:2181,192.168.2.205:2181                   # zookeeper注册中心的地址
     port: 2181                           # zookeeper注册中心的端口
   protocols:
     - name: dubbo
       serialization: hessian2
     - name: hessian 
   provider:
     retries: 0                           # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试
   consumer:                   # 公用的消费者配置
      lazy: true                #
      timeout: 100000             # 可选 性能调优 远程服务调用超时时间(毫秒) 1.0.16以上版本
      check: false               # 可选 服务治理 启动时检查提供者是否存在，true报错，false忽略 1.0.16以上版本
      
##################商家默认功能项是否开启配置##############################
merchant:
  aggregatepaystatus: 1 ###0: 表示关闭1:表示开启
  creditcardstatus: 0  ###0: 表示关闭1:表示开启
  customersaccumulatestatus: 1 ###0: 表示关闭1:表示开启
  phonesmessagestatus: 0 ###0: 表示关闭1:表示开启
  onlinestorestatus: 0 ###0: 表示关闭1:表示开启
  paybeforeadvertisingstatus: 0 ###0: 表示关闭1:表示开启
  receiptsstatus: 0 ###0: 表示关闭1:表示开启
  storemapstatus: 1 ###0: 表示关闭1:表示开启
  salesstatisticsstatus: 1 ###0: 表示关闭1:表示开启
  paymentdetailsstatus: 1 ###0: 表示关闭1:表示开启
  servicelinksstatus: 0 ###0: 表示关闭1:表示开启
  grantredpacketstatus: 0 ###0: 表示关闭1:表示开启
  groupsstatus: 1 ###0: 表示关闭1:表示开启
  payafteradvertisingstatus: 0 ###0: 表示关闭1:表示开启
  isdelete: 1 ###0: 表示关闭1:表示开启
