server:
  port: 8006
  display-name: bz_user
  clientNo: BZ00006
spring:  
  profiles:  
    active: test
################################################测试环境配置#######################################################
---                                                       
spring:
  profiles: test
  aop:
    proxy-target-class: true
###########数据源配置#######################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.202:3306/bz_user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: bztest
    password: bz123456
#############dubbo配置###########################    
  dubbo: 
   application:
     name: userService-provider
   base-package: com.bz.user.core.service # dubbo服务发布者所在的包
   registry:
     address: 192.168.2.202:2181,192.168.2.205:2181                   # zookeeper注册中心的地址
     port: 2181                           # zookeeper注册中心的端口
   protocols:
     - name: dubbo
       serialization: hessian2
     - name: hessian 
   provider:
     retries: 3                # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试
   consumer:                   # 公用的消费者配置
      lazy: false                #
      timeout: 30000             # 可选 性能调优 远程服务调用超时时间(毫秒) 1.0.16以上版本
      check: true               # 可选 服务治理 启动时检查提供者是否存在，true报错，false忽略 1.0.16以上版本     