server:
  port: 8013
  display-name: bz_open-web
  clientNo: BZ00010
spring:  
  profiles:  
    active: test
################################################测试环境配置#######################################################
---                                                       
spring:
  profiles: test
  dubbo: 
    application:
      name: manage-consumer
    base-package: com.bz.openweb  # dubbo服务调用者所在的包  
    registry:
      address: 192.168.2.202:2181,192.168.2.205:2181                 # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    protocols:
     - name: dubbo
       serialization: hessian2
     - name: hessian 
    consumer:
      timeout: 100000 
      check: false                          # 服务启动时检查被调用服务是否可用
      retries: 0                           # 服务调用重试次数 
  aop:
    proxy-target-class: true
  resources:
    static-locations:
      - classpath:/static/  
##########视图模板配置###############################################################################################
  freemarker:
    cache: true
    template-loader-path:
      - classpath:/templates/
    allow-request-override: false
    allow-session-override: false
    check-template-location: true
    charset: UTF-8
    enabled: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    request-context-attribute: request
    settings:
      number_format: 0.######
      boolean_format: true,false
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      object_wrapper: freemarker.ext.beans.BeansWrapper
      whitespace_stripping: true
      tag_syntax: square_bracket
      template_update_delay: 0
      classic_compatible: true
##########http配置########################
  http: 
   encoding:
      charset: UTF-8
##########json配置########################    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
###########缓存配置#######################    
  cache:
    type: ehcache
    ehcache: 
      config: classpath:ehcache.xml
##################线程池配置#################################################
  task:
    pool:
      core-pool-size: 5  #####线程池维护线程的最少数量
      keep-alive-seconds: 200 ###允许的空闲时间
      max-pool-size: 50    ##############线程池维护线程的最大数量
      queue-capacity: 20  ###缓存队列      
#################################加密配置#######################################################
encryption:
 webkey: ee52c7a300a2d6c66897ff23eb44f755654b89c766625cdc13a0e39a17b38a76652a52135d3ffa3347e838d61a72f975de141fedf7494d237f9b73bd56fd5f21  ###网页端请求加密配置##############
#################################微信端配置############################  
wechat:
  mp:
    appId: wxde4f8add6218b672
    secret: 583622a8e8297ef227e06b374c2530a4
    token:
    aesKey: 
  share:
    title: 宝众商城
    link: http://att397200731.eicp.net/merchant/registCode
    imgUrl: http://www.baozho.com/data/files/mall/settings/site_logo.png
    desc: 您身边的移动商城