server:
  port: 8002
  display-name: bz_third-party
  clientNo: BZ00002
spring:  
  profiles:  
    active: test
################################################测试环境配置#######################################################
---                                                       
spring:
  profiles: test
  aop:
    proxy-target-class: true
###########数据源配置#############################################################################################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.202:3306/bz_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: bztest
    password: bz123456
#############dubbo配置###########################    
  dubbo: 
   application:
     name: bz_third-party-provider
   base-package: com.bz.thirdparty.core.service  # dubbo服务发布者所在的包
   registry:
     address: 192.168.2.202:2181,192.168.2.205:2181                   # zookeeper注册中心的地址
     port: 2181                           # zookeeper注册中心的端口
   protocols:
     - name: dubbo
       serialization: hessian2
     - name: hessian 
   provider:
     retries: 0                           # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试
   consumer:
     timeout: 60000 
     check: false                          # 服务启动时检查被调用服务是否可用
     retries: 2                           # 服务调用重试次数 


##########视图模板配置###############################################################################################
  freemarker:
    cache: true
    template-loader-path:
      - classpath:/templates/
    allow-request-override: false
    allow-session-override: false
    check-template-location: true
    charset: UTF-8
    enabled: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    request-context-attribute: request
    settings:
      number_format: 0.######
      boolean_format: true,false
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      object_wrapper: freemarker.ext.beans.BeansWrapper
      whitespace_stripping: true
      tag_syntax: square_bracket
      template_update_delay: 0
      classic_compatible: true
###########缓存配置#######################    
  cache: 
   type: ehcache
   ehcache: 
    config: classpath:ehcache.xml 
#################################极光推送配置#########################################
  push:
    appKey: 4aa91009b45d31763d333463
    masterSecret: 948e92bc684b7dabdf99f708
#################################邮件服务配置############################################
  mail:
    host: smtp.163.com
    username: leverlance@163.com
    password: lan520jing
    properties:
     mail:
      smtp:
       auth: true
       starttls:
        enable: true
        required: true    
###################################短信平台配置####################################################
sms:
 apikey: 8826d1ae8b406a69106426db998313be                                   ###api请求key
 account: 'https://api.dingdongcloud.com/v1/user/get'             ###用户信息查询
 captcha: 'https://api.dingdongcloud.com/v1/sms/captcha/send'     ###验证码短信发送
 notice: 'https://api.dingdongcloud.com//v1/sms/notice/multi_send'###通知短信发送
 marketing: 'https://api.dingdongcloud.com/v1/sms/marketing/send'  ###营销短信发送
 send: 
   intervaltime: 60 ###同一手机号码短信发送时间间隔限制(单位秒)
   onedayfrequency: 5 ###同一手机号码短信一天能发送次数限制
 verificationcode:
   termofvalidity: 300000 ###验证码有效期
#################################极光推送配置#########################################
push:
  appKey: 4aa91009b45d31763d333463
  masterSecret: 948e92bc684b7dabdf99f708
 #################################微信配置#############################################
wechat:
 mp:
   #appId: wxc215e4f757e4bf52                      ###亿禹微信公众号
   #secret: 117654af0242b39e52022b2af40d2f50
   #appId: wxba198d911d6ea1aa                      ###宝众商城微信公众号
   #secret: 39099fc34d02210d248c5de7848c5c62
   appId: wxde4f8add6218b672                      ###宝众移动微信公众号
   secret: 583622a8e8297ef227e06b374c2530a4
   token:
   aesKey: 
 file:
   materialUrl: http://file.api.weixin.qq.com/cgi-bin/media/get
#################################邮件服务配置############################################
 mail:
  host: smtp.163.com
  username: 13896667100@163.com
  password: tp19931023+-*
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true
      required: true 
################################地图配置###############################################
map:
 key: d6b18081843571ac9e1fe1a18d93a8a3  ##宝众商城商家云图定点KEY：33328462dd7e166eb6c98a81cf9c3cc3####
 tableid: 59e70cf7afdf521e86a19029 ###测试云图Id##
 addMerchantInfoUrl: http://yuntuapi.amap.com/datamanage/data/create ##增加商户地图定点##
 deleteMerchantInfoUrl: http://yuntuapi.amap.com/datamanage/data/delete ##根据ID删除商户地址##
 updateMerchantInfoUrl: http://yuntuapi.amap.com/datamanage/data/update ##更新指定tableid，指定一条数据序列号_id的数据信息。##
 selectLocalityMerchantInfoUrl: http://yuntuapi.amap.com/datasearch/local ##本地检索请求地址##
 selectPeripheryMerchantInfoUrl: http://yuntuapi.amap.com/datasearch/around ##周边检索请求##
 selectPolygonMerchantInfoUrl: http://yuntuapi.amap.com/datasearch/polygon ##多边形检索请求##
 selectByIdMerchantInfoUrl: http://yuntuapi.amap.com/datasearch/id  ##id检索请求##
 slectByConditionMerchantInfoUrl: http://yuntuapi.amap.com/datamanage/data/list ##按照条件关键字查询##
