package com.bz.dao.pojo.user;

import com.bz.framework.pojo.base.BasePojo;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-11-24 17:12:35
  */
public class UserMessage extends BasePojo {
    /**
     * 推送消息ID
     * 表字段 : user_message.id
     */
    private Integer id;

    /**
     * 用户ID
     * 表字段 : user_message.userid
     */
    private Integer userid;

    /**
     * 
     * 表字段 : user_message.shopId
     */
    private Integer shopid;

    /**
     * 推送消息标题
     * 表字段 : user_message.title
     */
    private String title;

    /**
     * 推送消息内容
     * 表字段 : user_message.content
     */
    private String content;

    /**
     * 私有消息;0：私有消息,1:公有消息
     * 表字段 : user_message.isprivately
     */
    private Integer isprivately;

    /**
     * 创建时间
     * 表字段 : user_message.createtime
     */
    private Date createtime;

    /**
     * 是否删除;0:否;1:删除
     * 表字段 : user_message.isdelete
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_message
     *
     * @mbg.generated Fri Nov 24 17:12:35 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 推送消息ID 字段:user_message.id
     *
     * @return user_message.id, 推送消息ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 推送消息ID 字段:user_message.id
     *
     * @param id the value for user_message.id, 推送消息ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 用户ID 字段:user_message.userid
     *
     * @return user_message.userid, 用户ID
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * 设置 用户ID 字段:user_message.userid
     *
     * @param userid the value for user_message.userid, 用户ID
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * 获取  字段:user_message.shopId
     *
     * @return user_message.shopId, 
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * 设置  字段:user_message.shopId
     *
     * @param shopid the value for user_message.shopId, 
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * 获取 推送消息标题 字段:user_message.title
     *
     * @return user_message.title, 推送消息标题
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置 推送消息标题 字段:user_message.title
     *
     * @param title the value for user_message.title, 推送消息标题
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * 获取 推送消息内容 字段:user_message.content
     *
     * @return user_message.content, 推送消息内容
     */
    public String getContent() {
        return content;
    }

    /**
     * 设置 推送消息内容 字段:user_message.content
     *
     * @param content the value for user_message.content, 推送消息内容
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 获取 私有消息;0：私有消息,1:公有消息 字段:user_message.isprivately
     *
     * @return user_message.isprivately, 私有消息;0：私有消息,1:公有消息
     */
    public Integer getIsprivately() {
        return isprivately;
    }

    /**
     * 设置 私有消息;0：私有消息,1:公有消息 字段:user_message.isprivately
     *
     * @param isprivately the value for user_message.isprivately, 私有消息;0：私有消息,1:公有消息
     */
    public void setIsprivately(Integer isprivately) {
        this.isprivately = isprivately;
    }

    /**
     * 获取 创建时间 字段:user_message.createtime
     *
     * @return user_message.createtime, 创建时间
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 设置 创建时间 字段:user_message.createtime
     *
     * @param createtime the value for user_message.createtime, 创建时间
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * 获取 是否删除;0:否;1:删除 字段:user_message.isdelete
     *
     * @return user_message.isdelete, 是否删除;0:否;1:删除
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * 设置 是否删除;0:否;1:删除 字段:user_message.isdelete
     *
     * @param isdelete the value for user_message.isdelete, 是否删除;0:否;1:删除
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}