package com.bz.dao.pojo.user;

import com.bz.framework.pojo.base.BasePojo;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-11-23 09:58:18
  */
public class UserBase extends BasePojo {
    /**
     * 用户ID
     * 表字段 : user_base.id
     */
    private Integer id;

    /**
     * 用户编号
     * 表字段 : user_base.number
     */
    private String number;

    /**
     * 用户名称
     * 表字段 : user_base.name
     */
    private String name;

    /**
     * 推送标识
     * 表字段 : user_base.pushId
     */
    private String pushid;

    /**
     * 省级ID
     * 表字段 : user_base.provinceId
     */
    private Integer provinceid;

    /**
     * 区级ID
     * 表字段 : user_base.districtId
     */
    private Integer districtid;

    /**
     * 县级ID
     * 表字段 : user_base.countyId
     */
    private Integer countyid;

    /**
     * 用户微信号
     * 表字段 : user_base.weChatNo
     */
    private String wechatno;

    /**
     * 微信名称
     * 表字段 : user_base.weChatName
     */
    private String wechatname;

    /**
     * 微信openID
     * 表字段 : user_base.weChatOpenId
     */
    private String wechatopenid;

    /**
     * 微信头像
     * 表字段 : user_base.weChatImage
     */
    private String wechatimage;

    /**
     * 支付宝ID
     * 表字段 : user_base.alipayId
     */
    private String alipayid;

    /**
     * 支付宝号
     * 表字段 : user_base.alipayNo
     */
    private String alipayno;

    /**
     * 支付宝名称
     * 表字段 : user_base.alipayName
     */
    private String alipayname;

    /**
     * 支付宝头像地址
     * 表字段 : user_base.alipayImage
     */
    private String alipayimage;

    /**
     * 用户类型;1:普通用户；2：代理商;3:店铺用户；4：网店用户
     * 表字段 : user_base.type
     */
    private String type;

    /**
     * 创建时间
     * 表字段 : user_base.createTime
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbg.generated Thu Nov 23 09:58:18 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 用户ID 字段:user_base.id
     *
     * @return user_base.id, 用户ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 用户ID 字段:user_base.id
     *
     * @param id the value for user_base.id, 用户ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 用户编号 字段:user_base.number
     *
     * @return user_base.number, 用户编号
     */
    public String getNumber() {
        return number;
    }

    /**
     * 设置 用户编号 字段:user_base.number
     *
     * @param number the value for user_base.number, 用户编号
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * 获取 用户名称 字段:user_base.name
     *
     * @return user_base.name, 用户名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 用户名称 字段:user_base.name
     *
     * @param name the value for user_base.name, 用户名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取 推送标识 字段:user_base.pushId
     *
     * @return user_base.pushId, 推送标识
     */
    public String getPushid() {
        return pushid;
    }

    /**
     * 设置 推送标识 字段:user_base.pushId
     *
     * @param pushid the value for user_base.pushId, 推送标识
     */
    public void setPushid(String pushid) {
        this.pushid = pushid;
    }

    /**
     * 获取 省级ID 字段:user_base.provinceId
     *
     * @return user_base.provinceId, 省级ID
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * 设置 省级ID 字段:user_base.provinceId
     *
     * @param provinceid the value for user_base.provinceId, 省级ID
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * 获取 区级ID 字段:user_base.districtId
     *
     * @return user_base.districtId, 区级ID
     */
    public Integer getDistrictid() {
        return districtid;
    }

    /**
     * 设置 区级ID 字段:user_base.districtId
     *
     * @param districtid the value for user_base.districtId, 区级ID
     */
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }

    /**
     * 获取 县级ID 字段:user_base.countyId
     *
     * @return user_base.countyId, 县级ID
     */
    public Integer getCountyid() {
        return countyid;
    }

    /**
     * 设置 县级ID 字段:user_base.countyId
     *
     * @param countyid the value for user_base.countyId, 县级ID
     */
    public void setCountyid(Integer countyid) {
        this.countyid = countyid;
    }

    /**
     * 获取 用户微信号 字段:user_base.weChatNo
     *
     * @return user_base.weChatNo, 用户微信号
     */
    public String getWechatno() {
        return wechatno;
    }

    /**
     * 设置 用户微信号 字段:user_base.weChatNo
     *
     * @param wechatno the value for user_base.weChatNo, 用户微信号
     */
    public void setWechatno(String wechatno) {
        this.wechatno = wechatno;
    }

    /**
     * 获取 微信名称 字段:user_base.weChatName
     *
     * @return user_base.weChatName, 微信名称
     */
    public String getWechatname() {
        return wechatname;
    }

    /**
     * 设置 微信名称 字段:user_base.weChatName
     *
     * @param wechatname the value for user_base.weChatName, 微信名称
     */
    public void setWechatname(String wechatname) {
        this.wechatname = wechatname;
    }

    /**
     * 获取 微信openID 字段:user_base.weChatOpenId
     *
     * @return user_base.weChatOpenId, 微信openID
     */
    public String getWechatopenid() {
        return wechatopenid;
    }

    /**
     * 设置 微信openID 字段:user_base.weChatOpenId
     *
     * @param wechatopenid the value for user_base.weChatOpenId, 微信openID
     */
    public void setWechatopenid(String wechatopenid) {
        this.wechatopenid = wechatopenid;
    }

    /**
     * 获取 微信头像 字段:user_base.weChatImage
     *
     * @return user_base.weChatImage, 微信头像
     */
    public String getWechatimage() {
        return wechatimage;
    }

    /**
     * 设置 微信头像 字段:user_base.weChatImage
     *
     * @param wechatimage the value for user_base.weChatImage, 微信头像
     */
    public void setWechatimage(String wechatimage) {
        this.wechatimage = wechatimage;
    }

    /**
     * 获取 支付宝ID 字段:user_base.alipayId
     *
     * @return user_base.alipayId, 支付宝ID
     */
    public String getAlipayid() {
        return alipayid;
    }

    /**
     * 设置 支付宝ID 字段:user_base.alipayId
     *
     * @param alipayid the value for user_base.alipayId, 支付宝ID
     */
    public void setAlipayid(String alipayid) {
        this.alipayid = alipayid;
    }

    /**
     * 获取 支付宝号 字段:user_base.alipayNo
     *
     * @return user_base.alipayNo, 支付宝号
     */
    public String getAlipayno() {
        return alipayno;
    }

    /**
     * 设置 支付宝号 字段:user_base.alipayNo
     *
     * @param alipayno the value for user_base.alipayNo, 支付宝号
     */
    public void setAlipayno(String alipayno) {
        this.alipayno = alipayno;
    }

    /**
     * 获取 支付宝名称 字段:user_base.alipayName
     *
     * @return user_base.alipayName, 支付宝名称
     */
    public String getAlipayname() {
        return alipayname;
    }

    /**
     * 设置 支付宝名称 字段:user_base.alipayName
     *
     * @param alipayname the value for user_base.alipayName, 支付宝名称
     */
    public void setAlipayname(String alipayname) {
        this.alipayname = alipayname;
    }

    /**
     * 获取 支付宝头像地址 字段:user_base.alipayImage
     *
     * @return user_base.alipayImage, 支付宝头像地址
     */
    public String getAlipayimage() {
        return alipayimage;
    }

    /**
     * 设置 支付宝头像地址 字段:user_base.alipayImage
     *
     * @param alipayimage the value for user_base.alipayImage, 支付宝头像地址
     */
    public void setAlipayimage(String alipayimage) {
        this.alipayimage = alipayimage;
    }

    /**
     * 获取 用户类型;1:普通用户；2：代理商;3:店铺用户；4：网店用户 字段:user_base.type
     *
     * @return user_base.type, 用户类型;1:普通用户；2：代理商;3:店铺用户；4：网店用户
     */
    public String getType() {
        return type;
    }

    /**
     * 设置 用户类型;1:普通用户；2：代理商;3:店铺用户；4：网店用户 字段:user_base.type
     *
     * @param type the value for user_base.type, 用户类型;1:普通用户；2：代理商;3:店铺用户；4：网店用户
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * 获取 创建时间 字段:user_base.createTime
     *
     * @return user_base.createTime, 创建时间
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 设置 创建时间 字段:user_base.createTime
     *
     * @param createtime the value for user_base.createTime, 创建时间
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}