package com.bz.dao.pojo.order;

import com.bz.framework.pojo.base.BasePojo;
import java.math.BigDecimal;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-11-15 15:50:09
  */
public class OrderBase extends BasePojo {
    /**
     * 订单ID
     * 表字段 : order_base.id
     */
    private Integer id;

    /**
     * 订单编号
     * 表字段 : order_base.orderNo
     */
    private String orderno;

    /**
     * 订单关联用户ID
     * 表字段 : order_base.userId
     */
    private Integer userid;

    /**
     * 订单关联店铺ID
     * 表字段 : order_base.shopId
     */
    private Integer shopid;

    /**
     * 订单总额
     * 表字段 : order_base.tatolMoney
     */
    private BigDecimal tatolmoney;

    /**
     * 线上支付总额
     * 表字段 : order_base.onlinePayMoney
     */
    private BigDecimal onlinepaymoney;

    /**
     * 线下付款总额
     * 表字段 : order_base.offlinePayMoney
     */
    private BigDecimal offlinepaymoney;

    /**
     * 活动抵用总额
     * 表字段 : order_base.activityPayMoney
     */
    private BigDecimal activitypaymoney;

    /**
     * 积分抵用金额
     * 表字段 : order_base.integralPayMoney
     */
    private BigDecimal integralpaymoney;

    /**
     * 支付状态:1001:订单初始化；1002:订单支付超时; 1003:订单支付失败; 1004:订单支付成功; 1005:订单创建异常
     * 表字段 : order_base.payState
     */
    private Integer paystate;

    /**
     * 支付方式；1：微信支付；2：支付宝支付；3：混合支付；
     * 表字段 : order_base.payWay
     */
    private Integer payway;

    /**
     * 支付结果回调时间
     * 表字段 : order_base.callBackTime
     */
    private Date callbacktime;

    /**
     * 支付备注
     * 表字段 : order_base.payRemark
     */
    private String payremark;

    /**
     * 订单创建时间
     * 表字段 : order_base.createTime
     */
    private Date createtime;

    /**
     * 是否隐藏；0：展示；1：隐藏
     * 表字段 : order_base.isShow
     */
    private Integer isshow;

    /**
     * 订单类型;1：扫码订单；2网店订单
     * 表字段 : order_base.orderType
     */
    private Integer ordertype;

    /**
     * 二维码地址
     * 表字段 : order_base.qrCodeLink
     */
    private String qrcodelink;

    /**
     * 客户端IP
     * 表字段 : order_base.clientIp
     */
    private String clientip;

    /**
     * 签名字符串
     * 表字段 : order_base.signStr
     */
    private String signstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_base
     *
     * @mbg.generated Wed Nov 15 15:50:09 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 订单ID 字段:order_base.id
     *
     * @return order_base.id, 订单ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 订单ID 字段:order_base.id
     *
     * @param id the value for order_base.id, 订单ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 订单编号 字段:order_base.orderNo
     *
     * @return order_base.orderNo, 订单编号
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * 设置 订单编号 字段:order_base.orderNo
     *
     * @param orderno the value for order_base.orderNo, 订单编号
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * 获取 订单关联用户ID 字段:order_base.userId
     *
     * @return order_base.userId, 订单关联用户ID
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * 设置 订单关联用户ID 字段:order_base.userId
     *
     * @param userid the value for order_base.userId, 订单关联用户ID
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * 获取 订单关联店铺ID 字段:order_base.shopId
     *
     * @return order_base.shopId, 订单关联店铺ID
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * 设置 订单关联店铺ID 字段:order_base.shopId
     *
     * @param shopid the value for order_base.shopId, 订单关联店铺ID
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * 获取 订单总额 字段:order_base.tatolMoney
     *
     * @return order_base.tatolMoney, 订单总额
     */
    public BigDecimal getTatolmoney() {
        return tatolmoney;
    }

    /**
     * 设置 订单总额 字段:order_base.tatolMoney
     *
     * @param tatolmoney the value for order_base.tatolMoney, 订单总额
     */
    public void setTatolmoney(BigDecimal tatolmoney) {
        this.tatolmoney = tatolmoney;
    }

    /**
     * 获取 线上支付总额 字段:order_base.onlinePayMoney
     *
     * @return order_base.onlinePayMoney, 线上支付总额
     */
    public BigDecimal getOnlinepaymoney() {
        return onlinepaymoney;
    }

    /**
     * 设置 线上支付总额 字段:order_base.onlinePayMoney
     *
     * @param onlinepaymoney the value for order_base.onlinePayMoney, 线上支付总额
     */
    public void setOnlinepaymoney(BigDecimal onlinepaymoney) {
        this.onlinepaymoney = onlinepaymoney;
    }

    /**
     * 获取 线下付款总额 字段:order_base.offlinePayMoney
     *
     * @return order_base.offlinePayMoney, 线下付款总额
     */
    public BigDecimal getOfflinepaymoney() {
        return offlinepaymoney;
    }

    /**
     * 设置 线下付款总额 字段:order_base.offlinePayMoney
     *
     * @param offlinepaymoney the value for order_base.offlinePayMoney, 线下付款总额
     */
    public void setOfflinepaymoney(BigDecimal offlinepaymoney) {
        this.offlinepaymoney = offlinepaymoney;
    }

    /**
     * 获取 活动抵用总额 字段:order_base.activityPayMoney
     *
     * @return order_base.activityPayMoney, 活动抵用总额
     */
    public BigDecimal getActivitypaymoney() {
        return activitypaymoney;
    }

    /**
     * 设置 活动抵用总额 字段:order_base.activityPayMoney
     *
     * @param activitypaymoney the value for order_base.activityPayMoney, 活动抵用总额
     */
    public void setActivitypaymoney(BigDecimal activitypaymoney) {
        this.activitypaymoney = activitypaymoney;
    }

    /**
     * 获取 积分抵用金额 字段:order_base.integralPayMoney
     *
     * @return order_base.integralPayMoney, 积分抵用金额
     */
    public BigDecimal getIntegralpaymoney() {
        return integralpaymoney;
    }

    /**
     * 设置 积分抵用金额 字段:order_base.integralPayMoney
     *
     * @param integralpaymoney the value for order_base.integralPayMoney, 积分抵用金额
     */
    public void setIntegralpaymoney(BigDecimal integralpaymoney) {
        this.integralpaymoney = integralpaymoney;
    }

    /**
     * 获取 支付状态:1001:订单初始化；1002:订单支付超时; 1003:订单支付失败; 1004:订单支付成功; 1005:订单创建异常 字段:order_base.payState
     *
     * @return order_base.payState, 支付状态:1001:订单初始化；1002:订单支付超时; 1003:订单支付失败; 1004:订单支付成功; 1005:订单创建异常
     */
    public Integer getPaystate() {
        return paystate;
    }

    /**
     * 设置 支付状态:1001:订单初始化；1002:订单支付超时; 1003:订单支付失败; 1004:订单支付成功; 1005:订单创建异常 字段:order_base.payState
     *
     * @param paystate the value for order_base.payState, 支付状态:1001:订单初始化；1002:订单支付超时; 1003:订单支付失败; 1004:订单支付成功; 1005:订单创建异常
     */
    public void setPaystate(Integer paystate) {
        this.paystate = paystate;
    }

    /**
     * 获取 支付方式；1：微信支付；2：支付宝支付；3：混合支付； 字段:order_base.payWay
     *
     * @return order_base.payWay, 支付方式；1：微信支付；2：支付宝支付；3：混合支付；
     */
    public Integer getPayway() {
        return payway;
    }

    /**
     * 设置 支付方式；1：微信支付；2：支付宝支付；3：混合支付； 字段:order_base.payWay
     *
     * @param payway the value for order_base.payWay, 支付方式；1：微信支付；2：支付宝支付；3：混合支付；
     */
    public void setPayway(Integer payway) {
        this.payway = payway;
    }

    /**
     * 获取 支付结果回调时间 字段:order_base.callBackTime
     *
     * @return order_base.callBackTime, 支付结果回调时间
     */
    public Date getCallbacktime() {
        return callbacktime;
    }

    /**
     * 设置 支付结果回调时间 字段:order_base.callBackTime
     *
     * @param callbacktime the value for order_base.callBackTime, 支付结果回调时间
     */
    public void setCallbacktime(Date callbacktime) {
        this.callbacktime = callbacktime;
    }

    /**
     * 获取 支付备注 字段:order_base.payRemark
     *
     * @return order_base.payRemark, 支付备注
     */
    public String getPayremark() {
        return payremark;
    }

    /**
     * 设置 支付备注 字段:order_base.payRemark
     *
     * @param payremark the value for order_base.payRemark, 支付备注
     */
    public void setPayremark(String payremark) {
        this.payremark = payremark;
    }

    /**
     * 获取 订单创建时间 字段:order_base.createTime
     *
     * @return order_base.createTime, 订单创建时间
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 设置 订单创建时间 字段:order_base.createTime
     *
     * @param createtime the value for order_base.createTime, 订单创建时间
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * 获取 是否隐藏；0：展示；1：隐藏 字段:order_base.isShow
     *
     * @return order_base.isShow, 是否隐藏；0：展示；1：隐藏
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * 设置 是否隐藏；0：展示；1：隐藏 字段:order_base.isShow
     *
     * @param isshow the value for order_base.isShow, 是否隐藏；0：展示；1：隐藏
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * 获取 订单类型;1：扫码订单；2网店订单 字段:order_base.orderType
     *
     * @return order_base.orderType, 订单类型;1：扫码订单；2网店订单
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * 设置 订单类型;1：扫码订单；2网店订单 字段:order_base.orderType
     *
     * @param ordertype the value for order_base.orderType, 订单类型;1：扫码订单；2网店订单
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * 获取 二维码地址 字段:order_base.qrCodeLink
     *
     * @return order_base.qrCodeLink, 二维码地址
     */
    public String getQrcodelink() {
        return qrcodelink;
    }

    /**
     * 设置 二维码地址 字段:order_base.qrCodeLink
     *
     * @param qrcodelink the value for order_base.qrCodeLink, 二维码地址
     */
    public void setQrcodelink(String qrcodelink) {
        this.qrcodelink = qrcodelink;
    }

    /**
     * 获取 客户端IP 字段:order_base.clientIp
     *
     * @return order_base.clientIp, 客户端IP
     */
    public String getClientip() {
        return clientip;
    }

    /**
     * 设置 客户端IP 字段:order_base.clientIp
     *
     * @param clientip the value for order_base.clientIp, 客户端IP
     */
    public void setClientip(String clientip) {
        this.clientip = clientip;
    }

    /**
     * 获取 签名字符串 字段:order_base.signStr
     *
     * @return order_base.signStr, 签名字符串
     */
    public String getSignstr() {
        return signstr;
    }

    /**
     * 设置 签名字符串 字段:order_base.signStr
     *
     * @param signstr the value for order_base.signStr, 签名字符串
     */
    public void setSignstr(String signstr) {
        this.signstr = signstr;
    }
}