package com.bz.dao.pojo.agent;

import com.bz.framework.pojo.base.BasePojo;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-11-20 14:07:56
  */
public class BzCorporateInfo extends BasePojo {
    /**
     * id引用个人信息表
     * 表字段 : bz_corporate_info.id
     */
    private Integer id;

    /**
     * 公司名字
     * 表字段 : bz_corporate_info.companyName
     */
    private String companyname;

    /**
     * 地区
     * 表字段 : bz_corporate_info.region
     */
    private String region;

    /**
     * 大地区id
     * 表字段 : bz_corporate_info.regionId1
     */
    private String regionid1;

    /**
     * 小地区id
     * 表字段 : bz_corporate_info.regionId2
     */
    private String regionid2;

    /**
     * 
     * 表字段 : bz_corporate_info.regionId3
     */
    private String regionid3;

    /**
     * 
     * 表字段 : bz_corporate_info.regionId4
     */
    private String regionid4;

    /**
     * 公司类型
     * 表字段 : bz_corporate_info.companyType
     */
    private String companytype;

    /**
     * 执照号
     * 表字段 : bz_corporate_info.licenceId
     */
    private String licenceid;

    /**
     * 税务登记号
     * 表字段 : bz_corporate_info.taxId
     */
    private String taxid;

    /**
     * 法定代表人
     * 表字段 : bz_corporate_info.legalName
     */
    private String legalname;

    /**
     * 许可证图片地址
     * 表字段 : bz_corporate_info.licenceImg
     */
    private String licenceimg;

    /**
     * 税务登记证图片地址
     * 表字段 : bz_corporate_info.taxImg
     */
    private String taximg;

    /**
     * 法律证书图片地址
     * 表字段 : bz_corporate_info.legelImg
     */
    private String legelimg;

    /**
     * 创建时间
     * 表字段 : bz_corporate_info.createTime
     */
    private String createtime;

    /**
     * 代理人区域
     * 表字段 : bz_corporate_info.agentRegion
     */
    private String agentregion;

    /**
     * 身份证正面照
     * 表字段 : bz_corporate_info.idCardImg
     */
    private String idcardimg;

    /**
     * 身份证反面照
     * 表字段 : bz_corporate_info.idCardImg2
     */
    private String idcardimg2;

    /**
     * 手持身份证照
     * 表字段 : bz_corporate_info.idCardImg3
     */
    private String idcardimg3;

    /**
     * 是否显示
     * 表字段 : bz_corporate_info.isDelete
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bz_corporate_info
     *
     * @mbg.generated Mon Nov 20 14:07:56 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 id引用个人信息表 字段:bz_corporate_info.id
     *
     * @return bz_corporate_info.id, id引用个人信息表
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 id引用个人信息表 字段:bz_corporate_info.id
     *
     * @param id the value for bz_corporate_info.id, id引用个人信息表
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 公司名字 字段:bz_corporate_info.companyName
     *
     * @return bz_corporate_info.companyName, 公司名字
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * 设置 公司名字 字段:bz_corporate_info.companyName
     *
     * @param companyname the value for bz_corporate_info.companyName, 公司名字
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * 获取 地区 字段:bz_corporate_info.region
     *
     * @return bz_corporate_info.region, 地区
     */
    public String getRegion() {
        return region;
    }

    /**
     * 设置 地区 字段:bz_corporate_info.region
     *
     * @param region the value for bz_corporate_info.region, 地区
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * 获取 大地区id 字段:bz_corporate_info.regionId1
     *
     * @return bz_corporate_info.regionId1, 大地区id
     */
    public String getRegionid1() {
        return regionid1;
    }

    /**
     * 设置 大地区id 字段:bz_corporate_info.regionId1
     *
     * @param regionid1 the value for bz_corporate_info.regionId1, 大地区id
     */
    public void setRegionid1(String regionid1) {
        this.regionid1 = regionid1;
    }

    /**
     * 获取 小地区id 字段:bz_corporate_info.regionId2
     *
     * @return bz_corporate_info.regionId2, 小地区id
     */
    public String getRegionid2() {
        return regionid2;
    }

    /**
     * 设置 小地区id 字段:bz_corporate_info.regionId2
     *
     * @param regionid2 the value for bz_corporate_info.regionId2, 小地区id
     */
    public void setRegionid2(String regionid2) {
        this.regionid2 = regionid2;
    }

    /**
     * 获取  字段:bz_corporate_info.regionId3
     *
     * @return bz_corporate_info.regionId3, 
     */
    public String getRegionid3() {
        return regionid3;
    }

    /**
     * 设置  字段:bz_corporate_info.regionId3
     *
     * @param regionid3 the value for bz_corporate_info.regionId3, 
     */
    public void setRegionid3(String regionid3) {
        this.regionid3 = regionid3;
    }

    /**
     * 获取  字段:bz_corporate_info.regionId4
     *
     * @return bz_corporate_info.regionId4, 
     */
    public String getRegionid4() {
        return regionid4;
    }

    /**
     * 设置  字段:bz_corporate_info.regionId4
     *
     * @param regionid4 the value for bz_corporate_info.regionId4, 
     */
    public void setRegionid4(String regionid4) {
        this.regionid4 = regionid4;
    }

    /**
     * 获取 公司类型 字段:bz_corporate_info.companyType
     *
     * @return bz_corporate_info.companyType, 公司类型
     */
    public String getCompanytype() {
        return companytype;
    }

    /**
     * 设置 公司类型 字段:bz_corporate_info.companyType
     *
     * @param companytype the value for bz_corporate_info.companyType, 公司类型
     */
    public void setCompanytype(String companytype) {
        this.companytype = companytype;
    }

    /**
     * 获取 执照号 字段:bz_corporate_info.licenceId
     *
     * @return bz_corporate_info.licenceId, 执照号
     */
    public String getLicenceid() {
        return licenceid;
    }

    /**
     * 设置 执照号 字段:bz_corporate_info.licenceId
     *
     * @param licenceid the value for bz_corporate_info.licenceId, 执照号
     */
    public void setLicenceid(String licenceid) {
        this.licenceid = licenceid;
    }

    /**
     * 获取 税务登记号 字段:bz_corporate_info.taxId
     *
     * @return bz_corporate_info.taxId, 税务登记号
     */
    public String getTaxid() {
        return taxid;
    }

    /**
     * 设置 税务登记号 字段:bz_corporate_info.taxId
     *
     * @param taxid the value for bz_corporate_info.taxId, 税务登记号
     */
    public void setTaxid(String taxid) {
        this.taxid = taxid;
    }

    /**
     * 获取 法定代表人 字段:bz_corporate_info.legalName
     *
     * @return bz_corporate_info.legalName, 法定代表人
     */
    public String getLegalname() {
        return legalname;
    }

    /**
     * 设置 法定代表人 字段:bz_corporate_info.legalName
     *
     * @param legalname the value for bz_corporate_info.legalName, 法定代表人
     */
    public void setLegalname(String legalname) {
        this.legalname = legalname;
    }

    /**
     * 获取 许可证图片地址 字段:bz_corporate_info.licenceImg
     *
     * @return bz_corporate_info.licenceImg, 许可证图片地址
     */
    public String getLicenceimg() {
        return licenceimg;
    }

    /**
     * 设置 许可证图片地址 字段:bz_corporate_info.licenceImg
     *
     * @param licenceimg the value for bz_corporate_info.licenceImg, 许可证图片地址
     */
    public void setLicenceimg(String licenceimg) {
        this.licenceimg = licenceimg;
    }

    /**
     * 获取 税务登记证图片地址 字段:bz_corporate_info.taxImg
     *
     * @return bz_corporate_info.taxImg, 税务登记证图片地址
     */
    public String getTaximg() {
        return taximg;
    }

    /**
     * 设置 税务登记证图片地址 字段:bz_corporate_info.taxImg
     *
     * @param taximg the value for bz_corporate_info.taxImg, 税务登记证图片地址
     */
    public void setTaximg(String taximg) {
        this.taximg = taximg;
    }

    /**
     * 获取 法律证书图片地址 字段:bz_corporate_info.legelImg
     *
     * @return bz_corporate_info.legelImg, 法律证书图片地址
     */
    public String getLegelimg() {
        return legelimg;
    }

    /**
     * 设置 法律证书图片地址 字段:bz_corporate_info.legelImg
     *
     * @param legelimg the value for bz_corporate_info.legelImg, 法律证书图片地址
     */
    public void setLegelimg(String legelimg) {
        this.legelimg = legelimg;
    }

    /**
     * 获取 创建时间 字段:bz_corporate_info.createTime
     *
     * @return bz_corporate_info.createTime, 创建时间
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * 设置 创建时间 字段:bz_corporate_info.createTime
     *
     * @param createtime the value for bz_corporate_info.createTime, 创建时间
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * 获取 代理人区域 字段:bz_corporate_info.agentRegion
     *
     * @return bz_corporate_info.agentRegion, 代理人区域
     */
    public String getAgentregion() {
        return agentregion;
    }

    /**
     * 设置 代理人区域 字段:bz_corporate_info.agentRegion
     *
     * @param agentregion the value for bz_corporate_info.agentRegion, 代理人区域
     */
    public void setAgentregion(String agentregion) {
        this.agentregion = agentregion;
    }

    /**
     * 获取 身份证正面照 字段:bz_corporate_info.idCardImg
     *
     * @return bz_corporate_info.idCardImg, 身份证正面照
     */
    public String getIdcardimg() {
        return idcardimg;
    }

    /**
     * 设置 身份证正面照 字段:bz_corporate_info.idCardImg
     *
     * @param idcardimg the value for bz_corporate_info.idCardImg, 身份证正面照
     */
    public void setIdcardimg(String idcardimg) {
        this.idcardimg = idcardimg;
    }

    /**
     * 获取 身份证反面照 字段:bz_corporate_info.idCardImg2
     *
     * @return bz_corporate_info.idCardImg2, 身份证反面照
     */
    public String getIdcardimg2() {
        return idcardimg2;
    }

    /**
     * 设置 身份证反面照 字段:bz_corporate_info.idCardImg2
     *
     * @param idcardimg2 the value for bz_corporate_info.idCardImg2, 身份证反面照
     */
    public void setIdcardimg2(String idcardimg2) {
        this.idcardimg2 = idcardimg2;
    }

    /**
     * 获取 手持身份证照 字段:bz_corporate_info.idCardImg3
     *
     * @return bz_corporate_info.idCardImg3, 手持身份证照
     */
    public String getIdcardimg3() {
        return idcardimg3;
    }

    /**
     * 设置 手持身份证照 字段:bz_corporate_info.idCardImg3
     *
     * @param idcardimg3 the value for bz_corporate_info.idCardImg3, 手持身份证照
     */
    public void setIdcardimg3(String idcardimg3) {
        this.idcardimg3 = idcardimg3;
    }

    /**
     * 获取 是否显示 字段:bz_corporate_info.isDelete
     *
     * @return bz_corporate_info.isDelete, 是否显示
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * 设置 是否显示 字段:bz_corporate_info.isDelete
     *
     * @param isdelete the value for bz_corporate_info.isDelete, 是否显示
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}