package com.bz.dao.pojo.agent;

import com.bz.framework.pojo.base.BasePojo;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-11-17 11:58:49
  */
public class BzIncidenceRelation extends BasePojo {
    /**
     * id为自增
     * 表字段 : bz_incidence_relation.id
     */
    private Integer id;

    /**
     * 用户id   引用个人信息表
     * 表字段 : bz_incidence_relation.userId
     */
    private String userid;

    /**
     * 被关联的用户id
     * 表字段 : bz_incidence_relation.refUserId
     */
    private String refuserid;

    /**
     * 创建时间
     * 表字段 : bz_incidence_relation.createTime
     */
    private String createtime;

    /**
     * 是否显示
     * 表字段 : bz_incidence_relation.isDelete
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bz_incidence_relation
     *
     * @mbg.generated Fri Nov 17 11:58:49 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 id为自增 字段:bz_incidence_relation.id
     *
     * @return bz_incidence_relation.id, id为自增
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 id为自增 字段:bz_incidence_relation.id
     *
     * @param id the value for bz_incidence_relation.id, id为自增
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 用户id   引用个人信息表 字段:bz_incidence_relation.userId
     *
     * @return bz_incidence_relation.userId, 用户id   引用个人信息表
     */
    public String getUserid() {
        return userid;
    }

    /**
     * 设置 用户id   引用个人信息表 字段:bz_incidence_relation.userId
     *
     * @param userid the value for bz_incidence_relation.userId, 用户id   引用个人信息表
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * 获取 被关联的用户id 字段:bz_incidence_relation.refUserId
     *
     * @return bz_incidence_relation.refUserId, 被关联的用户id
     */
    public String getRefuserid() {
        return refuserid;
    }

    /**
     * 设置 被关联的用户id 字段:bz_incidence_relation.refUserId
     *
     * @param refuserid the value for bz_incidence_relation.refUserId, 被关联的用户id
     */
    public void setRefuserid(String refuserid) {
        this.refuserid = refuserid;
    }

    /**
     * 获取 创建时间 字段:bz_incidence_relation.createTime
     *
     * @return bz_incidence_relation.createTime, 创建时间
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * 设置 创建时间 字段:bz_incidence_relation.createTime
     *
     * @param createtime the value for bz_incidence_relation.createTime, 创建时间
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * 获取 是否显示 字段:bz_incidence_relation.isDelete
     *
     * @return bz_incidence_relation.isDelete, 是否显示
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * 设置 是否显示 字段:bz_incidence_relation.isDelete
     *
     * @param isdelete the value for bz_incidence_relation.isDelete, 是否显示
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}