package com.bz.dao.pojo.agent;

import com.bz.framework.pojo.base.BasePojo;
import java.math.BigDecimal;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-11-17 11:59:27
  */
public class BzMovementOfFunds extends BasePojo {
    /**
     * 
     * 表字段 : bz_movement_of_funds.id
     */
    private Integer id;

    /**
     * 引用个人信息用户id
     * 表字段 : bz_movement_of_funds.userId
     */
    private String userid;

    /**
     * 资金变动备注
     * 表字段 : bz_movement_of_funds.reason
     */
    private String reason;

    /**
     * 
     * 表字段 : bz_movement_of_funds.createTime
     */
    private String createtime;

    /**
     * 是否锁定
     * 表字段 : bz_movement_of_funds.isLock
     */
    private Integer islock;

    /**
     * 
     * 表字段 : bz_movement_of_funds.change
     */
    private BigDecimal change;

    /**
     * 资金加或减
     * 表字段 : bz_movement_of_funds.upOrDown
     */
    private Integer upordown;

    /**
     * 是否显示
     * 表字段 : bz_movement_of_funds.isDelete
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bz_movement_of_funds
     *
     * @mbg.generated Fri Nov 17 11:59:27 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:bz_movement_of_funds.id
     *
     * @return bz_movement_of_funds.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:bz_movement_of_funds.id
     *
     * @param id the value for bz_movement_of_funds.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 引用个人信息用户id 字段:bz_movement_of_funds.userId
     *
     * @return bz_movement_of_funds.userId, 引用个人信息用户id
     */
    public String getUserid() {
        return userid;
    }

    /**
     * 设置 引用个人信息用户id 字段:bz_movement_of_funds.userId
     *
     * @param userid the value for bz_movement_of_funds.userId, 引用个人信息用户id
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * 获取 资金变动备注 字段:bz_movement_of_funds.reason
     *
     * @return bz_movement_of_funds.reason, 资金变动备注
     */
    public String getReason() {
        return reason;
    }

    /**
     * 设置 资金变动备注 字段:bz_movement_of_funds.reason
     *
     * @param reason the value for bz_movement_of_funds.reason, 资金变动备注
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * 获取  字段:bz_movement_of_funds.createTime
     *
     * @return bz_movement_of_funds.createTime, 
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * 设置  字段:bz_movement_of_funds.createTime
     *
     * @param createtime the value for bz_movement_of_funds.createTime, 
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * 获取 是否锁定 字段:bz_movement_of_funds.isLock
     *
     * @return bz_movement_of_funds.isLock, 是否锁定
     */
    public Integer getIslock() {
        return islock;
    }

    /**
     * 设置 是否锁定 字段:bz_movement_of_funds.isLock
     *
     * @param islock the value for bz_movement_of_funds.isLock, 是否锁定
     */
    public void setIslock(Integer islock) {
        this.islock = islock;
    }

    /**
     * 获取  字段:bz_movement_of_funds.change
     *
     * @return bz_movement_of_funds.change, 
     */
    public BigDecimal getChange() {
        return change;
    }

    /**
     * 设置  字段:bz_movement_of_funds.change
     *
     * @param change the value for bz_movement_of_funds.change, 
     */
    public void setChange(BigDecimal change) {
        this.change = change;
    }

    /**
     * 获取 资金加或减 字段:bz_movement_of_funds.upOrDown
     *
     * @return bz_movement_of_funds.upOrDown, 资金加或减
     */
    public Integer getUpordown() {
        return upordown;
    }

    /**
     * 设置 资金加或减 字段:bz_movement_of_funds.upOrDown
     *
     * @param upordown the value for bz_movement_of_funds.upOrDown, 资金加或减
     */
    public void setUpordown(Integer upordown) {
        this.upordown = upordown;
    }

    /**
     * 获取 是否显示 字段:bz_movement_of_funds.isDelete
     *
     * @return bz_movement_of_funds.isDelete, 是否显示
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * 设置 是否显示 字段:bz_movement_of_funds.isDelete
     *
     * @param isdelete the value for bz_movement_of_funds.isDelete, 是否显示
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}