package com.bz.dao.pojo.agent;

import com.bz.framework.pojo.base.BasePojo;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-11-17 12:00:31
  */
public class BzPayInfo extends BasePojo {
    /**
     * 引用个人信息id
     * 表字段 : bz_pay_info.id
     */
    private Integer id;

    /**
     * 创建时间
     * 表字段 : bz_pay_info.createTime
     */
    private String createtime;

    /**
     * 支付状态
     * 表字段 : bz_pay_info.paymentState
     */
    private String paymentstate;

    /**
     * 支付备注
     * 表字段 : bz_pay_info.paymentReason
     */
    private String paymentreason;

    /**
     * 收款账号
     * 表字段 : bz_pay_info.paymentAccount
     */
    private String paymentaccount;

    /**
     * 是否显示
     * 表字段 : bz_pay_info.isShow
     */
    private Integer isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bz_pay_info
     *
     * @mbg.generated Fri Nov 17 12:00:31 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 引用个人信息id 字段:bz_pay_info.id
     *
     * @return bz_pay_info.id, 引用个人信息id
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 引用个人信息id 字段:bz_pay_info.id
     *
     * @param id the value for bz_pay_info.id, 引用个人信息id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 创建时间 字段:bz_pay_info.createTime
     *
     * @return bz_pay_info.createTime, 创建时间
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * 设置 创建时间 字段:bz_pay_info.createTime
     *
     * @param createtime the value for bz_pay_info.createTime, 创建时间
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * 获取 支付状态 字段:bz_pay_info.paymentState
     *
     * @return bz_pay_info.paymentState, 支付状态
     */
    public String getPaymentstate() {
        return paymentstate;
    }

    /**
     * 设置 支付状态 字段:bz_pay_info.paymentState
     *
     * @param paymentstate the value for bz_pay_info.paymentState, 支付状态
     */
    public void setPaymentstate(String paymentstate) {
        this.paymentstate = paymentstate;
    }

    /**
     * 获取 支付备注 字段:bz_pay_info.paymentReason
     *
     * @return bz_pay_info.paymentReason, 支付备注
     */
    public String getPaymentreason() {
        return paymentreason;
    }

    /**
     * 设置 支付备注 字段:bz_pay_info.paymentReason
     *
     * @param paymentreason the value for bz_pay_info.paymentReason, 支付备注
     */
    public void setPaymentreason(String paymentreason) {
        this.paymentreason = paymentreason;
    }

    /**
     * 获取 收款账号 字段:bz_pay_info.paymentAccount
     *
     * @return bz_pay_info.paymentAccount, 收款账号
     */
    public String getPaymentaccount() {
        return paymentaccount;
    }

    /**
     * 设置 收款账号 字段:bz_pay_info.paymentAccount
     *
     * @param paymentaccount the value for bz_pay_info.paymentAccount, 收款账号
     */
    public void setPaymentaccount(String paymentaccount) {
        this.paymentaccount = paymentaccount;
    }

    /**
     * 获取 是否显示 字段:bz_pay_info.isShow
     *
     * @return bz_pay_info.isShow, 是否显示
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * 设置 是否显示 字段:bz_pay_info.isShow
     *
     * @param isshow the value for bz_pay_info.isShow, 是否显示
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }
}