package com.bz.dao.pojo.agent;

import com.bz.framework.pojo.base.BasePojo;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-11-17 11:59:59
  */
public class BzPartnershipLaw extends BasePojo {
    /**
     * id
     * 表字段 : bz_partnership_law.id
     */
    private Integer id;

    /**
     * 类型名 拼音
     * 表字段 : bz_partnership_law.typeName
     */
    private String typename;

    /**
     * 合伙人类型
     * 表字段 : bz_partnership_law.agentName
     */
    private String agentname;

    /**
     * 开通费用
     * 表字段 : bz_partnership_law.agentMoeny
     */
    private Integer agentmoeny;

    /**
     * 收益百分比
     * 表字段 : bz_partnership_law.percentage
     */
    private Integer percentage;

    /**
     * 创建时间
     * 表字段 : bz_partnership_law.createTime
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bz_partnership_law
     *
     * @mbg.generated Fri Nov 17 11:59:59 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 id 字段:bz_partnership_law.id
     *
     * @return bz_partnership_law.id, id
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 id 字段:bz_partnership_law.id
     *
     * @param id the value for bz_partnership_law.id, id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 类型名 拼音 字段:bz_partnership_law.typeName
     *
     * @return bz_partnership_law.typeName, 类型名 拼音
     */
    public String getTypename() {
        return typename;
    }

    /**
     * 设置 类型名 拼音 字段:bz_partnership_law.typeName
     *
     * @param typename the value for bz_partnership_law.typeName, 类型名 拼音
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * 获取 合伙人类型 字段:bz_partnership_law.agentName
     *
     * @return bz_partnership_law.agentName, 合伙人类型
     */
    public String getAgentname() {
        return agentname;
    }

    /**
     * 设置 合伙人类型 字段:bz_partnership_law.agentName
     *
     * @param agentname the value for bz_partnership_law.agentName, 合伙人类型
     */
    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    /**
     * 获取 开通费用 字段:bz_partnership_law.agentMoeny
     *
     * @return bz_partnership_law.agentMoeny, 开通费用
     */
    public Integer getAgentmoeny() {
        return agentmoeny;
    }

    /**
     * 设置 开通费用 字段:bz_partnership_law.agentMoeny
     *
     * @param agentmoeny the value for bz_partnership_law.agentMoeny, 开通费用
     */
    public void setAgentmoeny(Integer agentmoeny) {
        this.agentmoeny = agentmoeny;
    }

    /**
     * 获取 收益百分比 字段:bz_partnership_law.percentage
     *
     * @return bz_partnership_law.percentage, 收益百分比
     */
    public Integer getPercentage() {
        return percentage;
    }

    /**
     * 设置 收益百分比 字段:bz_partnership_law.percentage
     *
     * @param percentage the value for bz_partnership_law.percentage, 收益百分比
     */
    public void setPercentage(Integer percentage) {
        this.percentage = percentage;
    }

    /**
     * 获取 创建时间 字段:bz_partnership_law.createTime
     *
     * @return bz_partnership_law.createTime, 创建时间
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * 设置 创建时间 字段:bz_partnership_law.createTime
     *
     * @param createtime the value for bz_partnership_law.createTime, 创建时间
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }
}