package com.bz.open.core.vo.request.merchant;

import java.util.Date;

import com.bz.framework.pojo.base.BasePojo;

public class MerchantRedpacketGrantRecordRequest extends BasePojo{
	/**
     * 领取红包记录ID
     * 表字段 : merchant_redpacket_grant_record.id
     */
    private Integer id;

    /**
     * 关联用户ID
     * 表字段 : merchant_redpacket_grant_record.userId
     */
    private Integer userid;

    /**
     * 红包券ID
     * 表字段 : merchant_redpacket_grant_record.rpId
     */
    private Integer rpid;

    /**
     * 商铺ID
     * 表字段 : merchant_redpacket_grant_record.shopId
     */
    private Integer shopid;

    /**
     * 关联订单编号
     * 表字段 : merchant_redpacket_grant_record.orderNo
     */
    private String orderno;

    /**
     * 领取时间
     * 表字段 : merchant_redpacket_grant_record.createTime
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant_redpacket_grant_record
     *
     * @mbg.generated Mon Nov 06 00:59:31 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 领取红包记录ID 字段:merchant_redpacket_grant_record.id
     *
     * @return merchant_redpacket_grant_record.id, 领取红包记录ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 领取红包记录ID 字段:merchant_redpacket_grant_record.id
     *
     * @param id the value for merchant_redpacket_grant_record.id, 领取红包记录ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 关联用户ID 字段:merchant_redpacket_grant_record.userId
     *
     * @return merchant_redpacket_grant_record.userId, 关联用户ID
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * 设置 关联用户ID 字段:merchant_redpacket_grant_record.userId
     *
     * @param userid the value for merchant_redpacket_grant_record.userId, 关联用户ID
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * 获取 红包券ID 字段:merchant_redpacket_grant_record.rpId
     *
     * @return merchant_redpacket_grant_record.rpId, 红包券ID
     */
    public Integer getRpid() {
        return rpid;
    }

    /**
     * 设置 红包券ID 字段:merchant_redpacket_grant_record.rpId
     *
     * @param rpid the value for merchant_redpacket_grant_record.rpId, 红包券ID
     */
    public void setRpid(Integer rpid) {
        this.rpid = rpid;
    }

    /**
     * 获取 商铺ID 字段:merchant_redpacket_grant_record.shopId
     *
     * @return merchant_redpacket_grant_record.shopId, 商铺ID
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * 设置 商铺ID 字段:merchant_redpacket_grant_record.shopId
     *
     * @param shopid the value for merchant_redpacket_grant_record.shopId, 商铺ID
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * 获取 关联订单编号 字段:merchant_redpacket_grant_record.orderNo
     *
     * @return merchant_redpacket_grant_record.orderNo, 关联订单编号
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * 设置 关联订单编号 字段:merchant_redpacket_grant_record.orderNo
     *
     * @param orderno the value for merchant_redpacket_grant_record.orderNo, 关联订单编号
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * 获取 领取时间 字段:merchant_redpacket_grant_record.createTime
     *
     * @return merchant_redpacket_grant_record.createTime, 领取时间
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 设置 领取时间 字段:merchant_redpacket_grant_record.createTime
     *
     * @param createtime the value for merchant_redpacket_grant_record.createTime, 领取时间
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}
