package com.bz.dao.pojo.upload;

import com.bz.framework.pojo.base.BasePojo;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-09-30 16:59:09
  */
public class UploadFileInfo extends BasePojo {
    /**
     * 上传文件Id
     * 表字段 : system_upload_file_info.uploadFileId
     */
    private Long uploadFileId;

    /**
     * 上传文件类型Id
     * 表字段 : system_upload_file_info.uploadTypeId
     */
    private Integer uploadTypeId;

    /**
     * 服务地址
     * 表字段 : system_upload_file_info.serverUrl
     */
    private String serverUrl;

    /**
     * 原始文件地址
     * 表字段 : system_upload_file_info.baseFileUrl
     */
    private String baseFileUrl;

    /**
     * 文件大小(字节)
     * 表字段 : system_upload_file_info.size
     */
    private Long size;

    /**
     * 文件扩展名
     * 表字段 : system_upload_file_info.extName
     */
    private String extName;

    /**
     * 是否删除：0未删除；1已删除
     * 表字段 : system_upload_file_info.isDelete
     */
    private Byte isDelete;

    /**
     * 最后读取时间
     * 表字段 : system_upload_file_info.lastReadTime
     */
    private Integer lastReadTime;

    /**
     * API客户编号
     * 表字段 : system_upload_file_info.apiClientNo
     */
    private String apiClientNo;

    /**
     * 创建时间
     * 表字段 : system_upload_file_info.createTime
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_upload_file_info
     *
     * @mbg.generated Sat Sep 30 16:59:09 CST 2017
     */
    private static final long serialVersionUID = 1L;

	public Long getUploadFileId() {
		return uploadFileId;
	}

	public void setUploadFileId(Long uploadFileId) {
		this.uploadFileId = uploadFileId;
	}

	public Integer getUploadTypeId() {
		return uploadTypeId;
	}

	public void setUploadTypeId(Integer uploadTypeId) {
		this.uploadTypeId = uploadTypeId;
	}

	public String getServerUrl() {
		return serverUrl;
	}

	public void setServerUrl(String serverUrl) {
		this.serverUrl = serverUrl;
	}

	public String getBaseFileUrl() {
		return baseFileUrl;
	}

	public void setBaseFileUrl(String baseFileUrl) {
		this.baseFileUrl = baseFileUrl;
	}

	public Long getSize() {
		return size;
	}

	public void setSize(Long size) {
		this.size = size;
	}

	public String getExtName() {
		return extName;
	}

	public void setExtName(String extName) {
		this.extName = extName;
	}

	public Byte getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(Byte isDelete) {
		this.isDelete = isDelete;
	}

	public Integer getLastReadTime() {
		return lastReadTime;
	}

	public void setLastReadTime(Integer lastReadTime) {
		this.lastReadTime = lastReadTime;
	}

	public String getApiClientNo() {
		return apiClientNo;
	}

	public void setApiClientNo(String apiClientNo) {
		this.apiClientNo = apiClientNo;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}
   