package com.bz.dao.pojo.upload;

import com.bz.framework.pojo.base.BasePojo;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-09-30 16:58:26
  */
public class UploadFileDetail extends BasePojo {
    /**
     * Id
     * 表字段 : system_upload_file_detail.id
     */
    private Long id;

    /**
     * 上传文件Id
     * 表字段 : system_upload_file_detail.uploadFileId
     */
    private Long uploadfileid;

    /**
     * 文件尺寸规格
     * 表字段 : system_upload_file_detail.fileFormat
     */
    private Integer fileformat;

    /**
     * 服务地址
     * 表字段 : system_upload_file_detail.serverUrl
     */
    private String serverurl;

    /**
     * 文件大小(字节)
     * 表字段 : system_upload_file_detail.size
     */
    private Long size;

    /**
     * 文件地址
     * 表字段 : system_upload_file_detail.fileUrl
     */
    private String fileurl;

    /**
     * 文件扩展名
     * 表字段 : system_upload_file_detail.extName
     */
    private String extname;

    /**
     * 是否删除：0未删除；1已删除
     * 表字段 : system_upload_file_detail.isDelete
     */
    private Byte isdelete;

    /**
     * 创建时间
     * 表字段 : system_upload_file_detail.createTime
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_upload_file_detail
     *
     * @mbg.generated Sat Sep 30 16:58:26 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 Id 字段:system_upload_file_detail.id
     *
     * @return system_upload_file_detail.id, Id
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 Id 字段:system_upload_file_detail.id
     *
     * @param id the value for system_upload_file_detail.id, Id
     */
    public void setId(Long id) {
        this.id = id;
    }

	public Long getUploadfileid() {
		return uploadfileid;
	}

	public void setUploadfileid(Long uploadfileid) {
		this.uploadfileid = uploadfileid;
	}

	public Integer getFileformat() {
		return fileformat;
	}

	public void setFileformat(Integer fileformat) {
		this.fileformat = fileformat;
	}

	public String getServerurl() {
		return serverurl;
	}

	public void setServerurl(String serverurl) {
		this.serverurl = serverurl;
	}

	public Long getSize() {
		return size;
	}

	public void setSize(Long size) {
		this.size = size;
	}

	public String getFileurl() {
		return fileurl;
	}

	public void setFileurl(String fileurl) {
		this.fileurl = fileurl;
	}

	public String getExtname() {
		return extname;
	}

	public void setExtname(String extname) {
		this.extname = extname;
	}

	public Byte getIsdelete() {
		return isdelete;
	}

	public void setIsdelete(Byte isdelete) {
		this.isdelete = isdelete;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	

	
}